"""Repository interfaces (data-access contracts).

Services depend ONLY on these abstract bases. The active implementation is
chosen in `app/repositories/registry.py` — today SQLite, tomorrow MongoDB —
without touching any service or API code.
"""
from __future__ import annotations

import datetime as dt
from abc import ABC, abstractmethod
from typing import Any, Iterable

from app.schemas.common import (
    AlertOut,
    AnomalyOut,
    EventOut,
    GroundReportOut,
    MediaAnalyzeOut,
    SignalOut,
    SourceOut,
    UserOut,
)


class UserRepository(ABC):
    @abstractmethod
    def create(self, *, email: str, full_name: str, organization: str, hashed_password: str, role: str) -> UserOut: ...
    @abstractmethod
    def get_by_email(self, email: str) -> UserOut | None: ...
    @abstractmethod
    def get_by_id(self, user_id: str) -> UserOut | None: ...
    @abstractmethod
    def count(self) -> int: ...


class SourceRepository(ABC):
    @abstractmethod
    def list_all(self) -> list[SourceOut]: ...
    @abstractmethod
    def get(self, source_id: str) -> SourceOut | None: ...
    @abstractmethod
    def upsert_defaults(self, defaults: Iterable[dict[str, Any]]) -> None: ...
    @abstractmethod
    def touch_sync(self, source_id: str, *, latency_ms: int, status: str = "OPERATIONAL") -> None: ...
    @abstractmethod
    def set_mode(self, source_id: str, mode: str) -> None: ...
    @abstractmethod
    def search(self, q: str, limit: int = 8) -> list[SourceOut]: ...


class SignalRepository(ABC):
    @abstractmethod
    def create(self, data: dict[str, Any]) -> SignalOut: ...
    @abstractmethod
    def get(self, signal_id: str) -> SignalOut | None: ...
    @abstractmethod
    def list_page(self, *, filters: dict[str, Any], page: int, page_size: int, sort: str, direction: str) -> tuple[list[SignalOut], int]: ...
    @abstractmethod
    def update(self, signal_id: str, data: dict[str, Any]) -> None: ...
    @abstractmethod
    def count(self, filters: dict[str, Any] | None = None) -> int: ...
    @abstractmethod
    def recent(self, limit: int = 12, filters: dict[str, Any] | None = None) -> list[SignalOut]: ...
    @abstractmethod
    def candidates_for_duplicate_check(self, *, since: dt.datetime, limit: int = 500) -> list[SignalOut]: ...
    @abstractmethod
    def set_event(self, signal_ids: list[str], event_id: str | None) -> None: ...
    @abstractmethod
    def ids_for_event(self, event_id: str, limit: int = 400) -> list[SignalOut]: ...
    @abstractmethod
    def count_by_day(self, *, days: int, filters: dict[str, Any] | None = None) -> dict[str, int]: ...
    @abstractmethod
    def analytics_aggregates(self, filters: dict[str, Any] | None = None) -> dict[str, Any]: ...
    @abstractmethod
    def search(self, q: str, limit: int = 8) -> list[SignalOut]: ...
    @abstractmethod
    def assign_sequence(self, signal_id: str) -> int: ...
    @abstractmethod
    def get_by_sequence(self, seq: int) -> SignalOut | None: ...


class EventRepository(ABC):
    @abstractmethod
    def create(self, data: dict[str, Any]) -> EventOut: ...
    @abstractmethod
    def get(self, event_id: str) -> EventOut | None: ...
    @abstractmethod
    def update(self, event_id: str, data: dict[str, Any]) -> None: ...
    @abstractmethod
    def list_page(self, *, filters: dict[str, Any], page: int, page_size: int, sort: str, direction: str) -> tuple[list[EventOut], int]: ...
    @abstractmethod
    def list_all(self, filters: dict[str, Any] | None = None, limit: int = 500) -> list[EventOut]: ...
    @abstractmethod
    def count(self, filters: dict[str, Any] | None = None) -> int: ...
    @abstractmethod
    def search(self, q: str, limit: int = 8) -> list[EventOut]: ...
    @abstractmethod
    def open_event_near(self, *, event_type: str, latitude: float, longitude: float, radius_km: float, since: dt.datetime) -> EventOut | None: ...
    @abstractmethod
    def set_related(self, event_id: str, related_ids: list[str]) -> None: ...


class EvidenceRepository(ABC):
    @abstractmethod
    def replace_for_event(self, event_id: str, rows: list[dict[str, Any]]) -> None: ...
    @abstractmethod
    def list_for_event(self, event_id: str) -> list[dict[str, Any]]: ...


class GraphRepository(ABC):
    @abstractmethod
    def replace_for_event(self, event_id: str, edges: list[dict[str, Any]]) -> None: ...
    @abstractmethod
    def list_for_event(self, event_id: str) -> list[dict[str, Any]]: ...


class ObservationRepository(ABC):
    @abstractmethod
    def bulk_create(self, rows: list[dict[str, Any]]) -> int: ...
    @abstractmethod
    def series_for_city(self, city: str, metric: str, since: dt.datetime) -> list[dict[str, Any]]: ...
    @abstractmethod
    def stats_by_city(self, since: dt.datetime | None = None) -> list[dict[str, Any]]: ...


class VerificationRepository(ABC):
    @abstractmethod
    def create(self, data: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def list_for_event(self, event_id: str) -> list[dict[str, Any]]: ...
    @abstractmethod
    def recent(self, limit: int = 20) -> list[dict[str, Any]]: ...


class AlertRepository(ABC):
    @abstractmethod
    def create(self, data: dict[str, Any]) -> AlertOut: ...
    @abstractmethod
    def list_page(self, *, page: int, page_size: int, unread_only: bool = False) -> tuple[list[AlertOut], int]: ...
    @abstractmethod
    def mark_read(self, alert_id: str) -> None: ...
    @abstractmethod
    def mark_all_read(self) -> None: ...
    @abstractmethod
    def unread_count(self) -> int: ...


class AuditRepository(ABC):
    @abstractmethod
    def create(self, data: dict[str, Any]) -> str: ...
    @abstractmethod
    def recent(self, limit: int = 50) -> list[dict[str, Any]]: ...


class AnomalyRepository(ABC):
    @abstractmethod
    def replace_all(self, rows: list[dict[str, Any]]) -> int: ...
    @abstractmethod
    def list_all(self, *, limit: int = 200, state: str = "", risk: str = "", metric: str = "") -> list[AnomalyOut]: ...
    @abstractmethod
    def count(self) -> int: ...
    @abstractmethod
    def for_event(self, event_id: str) -> list[AnomalyOut]: ...
    @abstractmethod
    def link_event(self, anomaly_id: str, event_id: str) -> None: ...
    @abstractmethod
    def recent(self, limit: int = 12) -> list[AnomalyOut]: ...


class MediaRepository(ABC):
    @abstractmethod
    def create(self, data: dict[str, Any]) -> MediaAnalyzeOut: ...
    @abstractmethod
    def get(self, analysis_id: str) -> MediaAnalyzeOut | None: ...
    @abstractmethod
    def find_similar(self, phash: str, exclude_id: str | None = None, limit: int = 5) -> list[tuple[MediaAnalyzeOut, float]]: ...
    @abstractmethod
    def list_recent(self, limit: int = 50) -> list[MediaAnalyzeOut]: ...


class SimulationRepository(ABC):
    @abstractmethod
    def get_state(self) -> dict[str, Any]: ...
    @abstractmethod
    def update_state(self, data: dict[str, Any]) -> None: ...


class GroundReportRepository(ABC):
    @abstractmethod
    def create(self, data: dict[str, Any]) -> GroundReportOut: ...
    @abstractmethod
    def get_by_tracking(self, tracking_id: str) -> GroundReportOut | None: ...
    @abstractmethod
    def list_page(self, *, page: int, page_size: int) -> tuple[list[GroundReportOut], int]: ...
    @abstractmethod
    def set_status(self, report_id: str, status: str) -> None: ...
    @abstractmethod
    def count(self) -> int: ...


class UnitOfWork(ABC):
    """Boundary for transactions. SQLite impl wraps a session; Mongo impl
    will wrap a client session. Services call commit() at operation end."""

    @abstractmethod
    def commit(self) -> None: ...
    @abstractmethod
    def rollback(self) -> None: ...
